---
# Basic app information
app_name: readyanot-app
aws_ecr_url: 363599773651.dkr.ecr.ap-southeast-1.amazonaws.com

# Deployment branches
dev_branch: dev
prod_branch: main

# Elastic beanstalk environments
ebenv_dev: ReadyAnot-dev
ebenv_prod: ReadyAnot-prod

# Deployment information
branch_name: "{{ lookup('env', 'GITHUB_REF') | default('demo', True) | basename }}"
commit_hash: "{{ lookup('env', 'GITHUB_SHA') | default('demo', True) }}"
is_deploy: '{{ branch_name == prod_branch or branch_name == dev_branch }}'
is_local: "{{ branch_name == 'demo' }}"
